{
"grace": {"author_nick": "PIBIC-EM 2020", "author_name": "PIBIC-EM 2020", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"kathryn": {"author_nick": "PIBIC-EM 2020", "author_name": "PIBIC-EM 2020", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"natalia": {"author_nick": "PIBIC-EM 2020", "author_name": "PIBIC-EM 2020", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"parisa": {"author_nick": "PIBIC-EM 2020", "author_name": "PIBIC-EM 2020", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"samantha": {"author_nick": "PIBIC-EM 2020", "author_name": "PIBIC-EM 2020", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"alexa": {"author_nick": "PIBIC-EM 2020", "author_name": "PIBIC-EM 2020", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"lisa": {"author_nick": "Célula 21 Parte 0", "author_name": "Célula 21 Parte 3", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"callie": {"author_nick": "PIBIC-EM 2020", "author_name": "PIBIC-EM 2020", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"danae": {"author_nick": "S_Jerome", "author_name": "S_Jerome", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"roxanne": {"author_nick": "PIBIC-EM 2020", "author_name": "PIBIC-EM 2020", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"sara": {"author_nick": "PIBIC-EM 2020", "author_name": "PIBIC-EM 2020", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"stacy": {"author_nick": "Célula 22 Retículo", "author_name": "Célula 22 Retículo", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"meredith": {"author_nick": "PIBIC-EM 2020", "author_name": "PIBIC-EM 2020", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"libby": {"author_nick": "Jogo Célula 21", "author_name": "Jogo Célula 21", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"kellee": {"author_nick": "Célula 21 Parte 3", "author_name": "Célula 21 Parte 3", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"tracy": {"author_nick": "Célula 20 Parte 3", "author_name": "Célula 20 Parte 3", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"heather": {"author_nick": "Célula 22 Parte 3", "author_name": "Célula 22 Parte 3", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"naomi": {"author_nick": "Célula 22 Parte 6", "author_name": "Célula 22 Parte 6", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"amanda": {"author_nick": "Célula 22 Parte 10", "author_name": "Célula 22 Parte 10", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"sarah": {"author_nick": "Célula 22 Roteiro", "author_name": "Célula 22 Roteiro", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"courtney": {"author_nick": "Célula 21 Mochila", "author_name": "Célula 21 Mochila", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"ruzwana": {"author_nick": "Célula 21 - Itens", "author_name": "Célula 21 - Itens", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"soraya": {"author_nick": "Vila de Konoha", "author_name": "Vila de Konoha", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"julia": {"author_nick": "Mata 21", "author_name": "Mata 21", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"kristen": {"author_nick": "Coroinhas 21", "author_name": "Coroinhas 21", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"adda": {"author_nick": "Jesus 21", "author_name": "Jesus 21", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"anastasia": {"author_nick": "Puzzle 21", "author_name": "Puzzle 21", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
